export const athletes = [
  { id: 1, name: 'Brandon "Stronghold" Conley', division: 'Light Heavyweight', record: '2-0-1-1', age: 37 },
  { id: 2, name: 'Brandon Girtz', division: 'Lightweight', record: '1-2-0', age: 40 },
  { id: 3, name: 'Charisa "Sweetheart" Sigala', division: 'Strawweight', record: '1-5-1', age: 41 },
  { id: 4, name: 'Drako "The Great Drakolini" Rodriguez', division: 'Featherweight', record: '2-1-0', age: 29 },
  { id: 5, name: 'Dustin "The Disciple" Pague', division: 'Welterweight', record: '6-2-0', age: 38 },
  { id: 6, name: 'Francesco Ricchi', division: 'Middleweight', record: '7-3-0', age: 31 },
  { id: 7, name: 'Iman Williams', division: 'Light Heavyweight', record: '2-0-0', age: 32 },
  { id: 8, name: 'Jordan "Native Psycho" Griffin', division: 'Lightweight', record: '0-0-0', age: 35 },
  { id: 9, name: 'Josh "Cuddly Bear" Copeland', division: 'Heavyweight', record: '2-2-0', age: 43 },
  { id: 10, name: 'Josh "Predator" Freeman', division: 'Heavyweight', record: '0-1-0', age: 33 },
  { id: 11, name: 'Kasim "Caution" Ruffin', division: 'Featherweight / Bantamweight', record: '2-1-0', age: 32 },
  { id: 12, name: 'Lex Ludlow', division: 'Light Heavyweight', record: '2-0-0', age: 32 },
  { id: 13, name: 'Marcus "Bad Intentions" Edwards', division: 'Middleweight', record: '4-0-0', age: 36 },
  { id: 14, name: 'Nathan "The Reaper" Rivera', division: 'Featherweight', record: '5-0-0', age: 27 },
  { id: 15, name: 'Rickie "Crimson King" McConnico', division: 'Welterweight', record: '1-0-0', age: 27 },
  { id: 16, name: 'Sabah "The Sleek Sheik" Homasi', division: 'Middleweight', record: '1-2-0', age: 35 },
  { id: 17, name: 'Stanislav Grosu', division: 'Middleweight', record: '4-3-0', age: 32 },
  { id: 18, name: 'Steven "Savage" Sainsbury', division: 'Middleweight', record: '1-0-0', age: 32 },
  { id: 19, name: 'Sydney "Sundance" Smith', division: 'Strawweight', record: '1-3-0', age: 34 },
  { id: 20, name: 'Timothy "War" Teves', division: 'Lightweight', record: '0-0-0', age: 33 },
  { id: 21, name: 'Willie "Whoop Ass" Ramis Gates', division: 'Catchweight/Bantamweight', record: '1-0-0', age: 38 },
  { id: 22, name: 'Dan Moret', division: 'Middleweight', record: '0-0-0', age: 39 },
  { id: 23, name: 'Mike Bardsley', division: 'Featherweight', record: '0-0-0', age: 31 },
  { id: 24, name: 'Hunter Starner', division: 'Bantamweight', record: '0-0-0', age: 30 },
  { id: 25, name: 'Boston "Boom Boom" Salmon', division: 'Featherweight', record: '0-0-0', age: 35 },
  { id: 26, name: 'Mike Pope', division: 'Featherweight/Lightweight', record: '0-0-0', age: 37 },
  { id: 27, name: 'Ronny Hauser', division: 'Bantamweight', record: '1-0-0', age: 32 },
  { id: 28, name: 'Britain Hart', division: 'TBD', record: 'TBD', age: 0 },
]
